#!/usr/bin/python

import sys
from client.cmdparser import CmdParser
from client.shell import Shell

try:
    sys.argv[1]
    c = CmdParser(sys.argv)
    c.run()
except IndexError:
    s = Shell()
    s.cmdloop()
