#!/usr/bin/python

# Copyright (C) 2010-2014 by the Free Software Foundation, Inc.
#
# This file is part of mailman.client.
#
# mailman.client is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, version 3 of the License.
#
# mailman.client is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with mailman.client.  If not, see <http://www.gnu.org/licenses/>.
#
# This file is part of the Mailman CLI Project, Google Summer Of Code, 2014
#  
# Author    :   Rajeev S <rajeevs1992@gmail.com>
# Mentors   :   Stephen J. Turnbull <stephen@xemacs.org>
#               Abhilash Raj <raj.abhilash1@gmail.com>
#               Barry Warsaw <barry@list.org>

import sys
from mailmanclient.cli.lib.utils import Utils
from mailmanclient.cli.client.shell import Shell
from mailmanclient.cli.client.cmdparser import CmdParser
try:
    # If the mmclient is invoked with arguments, trigger the command
    # line tools, else trigger the commandline shell
    sys.argv[1]
    utils = Utils()
    arguments = None
    try:
        arguments = utils.stem(sys.argv)
    except IndexError:
        pass
    c = CmdParser(arguments)
    c.run()
except IndexError:
    # No arguments supplied.Start the shell.
    s = Shell()
    s.initialize()
    s.cmdloop()
